FROM rust:1.75 AS base

USER root

RUN \
  apt-get update \
  && apt-get install -y wget ca-certificates tzdata libpq-dev curl procps libuv1 libuv1-dev libssl-dev 

WORKDIR /app

COPY . .
RUN cargo build --features redis --release

ARG BIN_DIR=/local/bin
ARG BINARY=store

RUN mkdir -p ${BIN_DIR}

RUN cp /app/target/release/${BINARY} ${BIN_DIR}/${BINARY}

WORKDIR ${BIN_DIR}

CMD ./store
