{
 "title": "Model latency stats",
 "time": { "from": "2024-08-09T12:01:09.311Z", "to": "2024-08-09T12:01:30.911Z" },
 "panels": [
  {
   "title": "TP 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"CREATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent CREATE"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"UPDATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent UPDATE"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_tracker_bucket{model=\"payment_intent\", operation=\"FIND\"}[$__range])))",
     "legendFormat": "Payment_intent FIND"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"CREATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt CREATE"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"UPDATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt UPDATE"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"FIND_ALL\"}[$__range])))",
     "legendFormat": "Payment_attempt FIND_ALL"
    }
   ]
  },
  {
   "title": "TP 90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"CREATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent CREATE"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"UPDATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent UPDATE"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(latency_tracker_bucket{model=\"payment_intent\", operation=\"FIND\"}[$__range])))",
     "legendFormat": "Payment_intent FIND"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"CREATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt CREATE"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"UPDATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt UPDATE"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"FIND_ALL\"}[$__range])))",
     "legendFormat": "Payment_attempt FIND_ALL"
    }
   ]
  },
  {
   "title": "TP 50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"CREATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent CREATE"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(latency_tracker_bucket{model = \"payment_intent\", operation=\"UPDATE\"}[$__range])) by (le))",
     "legendFormat": "Payment_intent UPDATE"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(latency_tracker_bucket{model=\"payment_intent\", operation=\"FIND\"}[$__range])))",
     "legendFormat": "Payment_intent FIND"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"CREATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt CREATE"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"UPDATE\"}[$__range])))",
     "legendFormat": "PaymentAttempt UPDATE"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(latency_tracker_bucket{model=\"payment_attempt\", operation=\"FIND_ALL\"}[$__range])))",
     "legendFormat": "Payment_attempt FIND_ALL"
    }
   ]
  }
 ]
}